### ISSUE TITLE
Branding Patch API

### ISSUE THREAD

**Issue by SpaceWalkerRS** [OrnitheMC/ornithe-standard-libraries#16]
Currently the Branding Patch does not have an API, meaning mod developers cannot programmatically change the version and game branding, and the patch is taken solely from the launch arguments (which Fabric/Quilt Loader adds).

**Comment by AdelinaM17n** [comment]
How would we deal with multiple mods requesting a branding change? will there be a priority system or similar?

**Comment by SpaceWalkerRS** [comment]
We'll have to come up with a solution for that yeah. I imagine a priority system would be relatively straightforward, but we could even have more complex collision handling, where multiple messages are added after one another.
