### ISSUE TITLE
lifecycle-events Mixin crash on mc 1.4.7

### ISSUE THREAD

**Issue by repletsin5** [OrnitheMC/ornithe-standard-libraries#28]
[crash.txt](https://github.com/OrnitheMC/ornithe-standard-libraries/files/15143347/1.4.7crash.txt)

Crashes on start up
using jre 1.8 
also crashes with jre 17 with skipping compat checks.

**Comment by SpaceWalkerRS** [comment]
looks like you're mixing Legacy Fabric and Ornithe mods - Ornithe mods cannot be run on Legacy Fabric and vice versa

**Comment by repletsin5** [comment]
ooh my bad
